"""User id

Revision ID: 2ca723ecc8c0
Revises: 85f59ce17020
Create Date: 2025-11-12 14:15:40.762839

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2ca723ecc8c0"
down_revision: Union[str, Sequence[str], None] = "85f59ce17020"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("auth_user_id_key"), "auth", type_="unique")
    op.drop_column("auth", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "auth", sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.create_unique_constraint(
        op.f("auth_user_id_key"),
        "auth",
        ["user_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
